# Generated by Django 4.1.5 on 2023-01-21 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
